export const plan =[
    {
        id:1,
        value:'',
        label:'',
        selected:false
    },
    {
        id:2,
        value:'Free',
        label:'Free',
        selected:false
    },
    {
        id:3,
        value:'Standard',
        label:'Standard',
        selected:false
    },
    {
        id:4,
        value:'Preminum',
        label:'Premium',
        selected:false
    }
]
export const genres = [
    {
        id:1,
        name:'Comedy',
        value:'Comedy',
        checked:false
    },
    {
        id:2,
        name:'Action',
        value:'Action',
        checked:false
    },
    {
        id:3,
        name:'Drama',
        value:'Drama',
        checked:false
    },
    {
        id:4,
        name:'Fantasy',
        value:'Fantasy',
        checked:false
    },
    {
        id:5,
        name:'Horror',
        value:'Horror',
        checked:false
    },
    {
        id:6,
        name:'Mystery',
        value:'Mystery',
        checked:false
    },
    {
        id:7,
        name:'Romance',
        value:'Romance',
        checked:false
    },
    {
        id:8,
        name:'Thriller',
        value:'Thriller',
        checked:false
    },
    {
        id:9,
        name:'Sci Fi',
        value:'Sci Fi',
        checked:false
    },
    {
        id:10,
        name:'Crime',
        value:'Crime',
        checked:false
    },
    {
        id:11,
        name:'Sports',
        value:'Sports',
        checked:true
    },
]